driver:
  # this role only makes web requests to generate facts, so
  # provisioning is delegated; all work can be done on localhost
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: ocp_pull_secrets
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: true
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  # role tasks are delegated to localhost and idempotence is not needed
  # modify major sequences to no-op for create, destroy, and idempotence.
  create_sequence: []
  destroy_sequence: []
  converge_sequence:
    - converge
  check_sequence:
    - converge
    - check
  verify_sequence:
    - verify
  test_sequence:
    - lint
    - syntax
    - converge
    - verify
    - cleanup
verifier:
  name: testinfra
  options:
    v: true
  lint:
    name: flake8
